### ISSUE TITLE
production url is hard-coded

### ISSUE THREAD

**Issue by inwardvessel** [iotile/python_iotile_cloud#16]
https://github.com/iotile/python_iotile_cloud/blob/c59b26843d9039a1675eef86887dc4645fabb4cf/iotile_cloud/api/connection.py#L21

**Comment by dkarchmer** [comment]
This is by design. Only the default is hard coded.

But you can pass a different domain when you instantiate the `Api` class

e.g.

```
from iotile_cloud.api.connection import Api

# Default: Use https://iotile.cloud
api = Api()

# Custom Server
api = Api(domain='https://foo.bar')
```

Clossing
