### ISSUE TITLE
Add support for PATCH on device and sensorgraph API

### ISSUE THREAD

**Issue by timburke** [iotile/python_iotile_cloud#26]
This will allow testing downstream methods that require PATCHing resources on iotile.cloud

**Comment by x24ling** [comment]
Copied from https://github.com/iotile/coretools/issues/337#issuecomment-364211798

The mock_cloud may need to be modified to allow for patching the relevant APIs. I don't believe it has support for that right now. The mock_cloud implementation is here:

https://github.com/iotile/python_iotile_cloud/blob/master/iotile_cloud/utils/mock_cloud.py#L192

You can see an example of how we support handling a POST and the default GET there. You may need to modify the device API to add support for a PATCH.

**Comment by dkarchmer** [comment]
I think the specific line above is only relevant for /streamer/report/, which does not support PATCH (I don't thin).

I believe for `/api/v1/device` the current implementation will work as it will just return the same object (even if unmodified). If we want to properly emulate the PATCH, I think we need to modify

https://github.com/iotile/python_iotile_cloud/blob/d0883e79eebccddf12f50bdc49466a69fbc5a250/iotile_cloud/utils/mock_cloud.py#L265

and hopefully get the operation from the request object.

**Comment by timburke** [comment]
Yes, that is correct.  I wanted to just link to a line showing how to respond to multiple operations on an API but in this case it would need to be on one_object since that handles all of those apis.

**Comment by timburke** [comment]
Closed by PR #27
