### ISSUE TITLE
KeyError on streamer

### ISSUE THREAD

**Issue by inwardvessel** [iotile/python_iotile_cloud#28]
It seems this should be `last_id` instead of `highest_id`. @timburke can you confirm?
https://github.com/iotile/python_iotile_cloud/blob/4cd309944c3702a252e953cfcf199994c80aeab1/iotile_cloud/utils/mock_cloud.py#L266

**Comment by dkarchmer** [comment]
Yes, `last_id`

**Comment by timburke** [comment]
Correct yeah that's a bug
