### ISSUE TITLE
Add support for /report/generated/ API

### ISSUE THREAD

**Issue by timburke** [iotile/python_iotile_cloud#44]
API should allow us to test file uploads by returning a "signed" url that also points to `mock_cloud` and just captures what was uploaded.

**Comment by timburke** [comment]
@mattrunchey Since you're going to be in `mock_cloud` anyway can you also add API coverage so that we can test report uploading from `iotile_analytics` as well?

There are 3 apis + 1 special endpoint involved in report uploading:

- create_report: Notifies the cloud that we will be uploading a report gets an ID to track it
- get_signed_url: gets a URL and some key fields where we can do a PUT to upload each file in the report.  We then use this URL to do a PUT for each file in the report.
- finish_report: tells the cloud that we're done uploading files
- magic PUT url should just store what was posted there.  This is a front for a signed S3 URL that we directly upload to.

Example usage is this method here:
https://github.com/iotile/iotile_analytics/blob/ca8e88c5a3cd0b3d12a3e83a868a2c0901bc30be/iotile_analytics_interactive/iotile_analytics/interactive/reports/cloud_uploader.py#L27

We need the following APIs:
- POST `api/v1/report/generated`.  Posted data:

```
{
        'org': org_slug,
        'label': aribitrary_string_label,
        'source_ref': slug_of_device_or_archive_report_is_attached_to
}
```

Response is a JSON with a single "id" key that is a `uuid.uuid4()` containing the report's unique id.

- POST `api/v1/report/generated/{report_id}/uploadurl/`: Posted data:

```
{
    'name': file_name,
    'acl': 'public-read' if public is True else 'private',
    'content_type': self._get_mime_type(file_name)
}
```

Response is a JSON with `url` field that is the specific URL where we should do a multipart-formencoded put to upload the actual file.  The `fields` key has a `dict` of name/value strings that contains other form fields that we should include unmodified in the put request.  If these fields aren't included in the multipart PUT, it should be rejected with a 400 reponse.

- POST `/api/v1/report/generated/{report_id}/uploadsuccess/`: Posted data:
```
{
    'name': file_path
}
```

Response is JSON with a `url` key set that contains a link to the final report.

**Comment by mattrunchey** [comment]
I will add these endpoints along with the ota ones, thanks for pointing this out to me!
