### ISSUE TITLE
`mock_cloud` change seems to have broken coretools unit tests

### ISSUE THREAD

**Issue by timburke** [iotile/python_iotile_cloud#53]
See https://travis-ci.org/iotile/coretools/jobs/452641195

@x24ling @mattrunchey

**Comment by mattrunchey** [comment]
Coretools fix is in https://github.com/iotile/coretools/pull/578. unfortunately both repos are co-dependent on these tests. Probably not good design for the unit tests but shouldn't break normally, this is just an API change that wasn't expected.
