### ISSUE TITLE
Problem with login / logout

### ISSUE THREAD

**Issue by nockty** [iotile/python_iotile_cloud#54]
It seems there is a problem with login and logout functionalities. I can't log out and then log in again.

```python
>>> from iotile_cloud.api.connection import Api
>>> domain = XXXX
>>> email = YYYY
>>> password= ZZZZ
>>> api = Api(domain=domain)
>>> api.login(email=email, password=password)
[DEBUG] 2018-12-13 15:17:58,197 Starting new HTTP connection (1): XXXX
[DEBUG] 2018-12-13 15:17:58,460 XXXX "POST /api/v1/auth/login/ HTTP/1.1" 200 772
[DEBUG] 2018-12-13 15:17:58,461 Welcome @YYYY
True
>>> api.logout()
[DEBUG] 2018-12-13 15:18:06,855 Starting new HTTP connection (1): XXXX
[DEBUG] 2018-12-13 15:18:06,873 XXXX "POST /api/v1/auth/logout/ HTTP/1.1" 204 0
[DEBUG] 2018-12-13 15:18:06,874 Goodbye @YYYY
>>> api.login(email=email, password=password)
[DEBUG] 2018-12-13 15:18:14,735 Starting new HTTP connection (1): localhost:9000
[DEBUG] 2018-12-13 15:18:14,747 http://localhost:9000 "POST /api/v1/auth/login/ HTTP/1.1" 403 19
[ERROR] 2018-12-13 15:18:14,748 Login failed: 403 "Already Logged-in"
False
>>> 
```

**Comment by dkarchmer** [comment]
May be an issue with the cloud, but the 204 return status look good.
But the error indicates that the request.user.is_annonymous was not true. This will only be the case if you are passing a token as part of the login, but that should not be possible with the login() function in this API. Maybe some kind of caching

**Comment by nockty** [comment]
> May be an issue with the cloud, but the 204 return status look good.
> But the error indicates that the request.user.is_annonymous was not true. This will only be the case if you are passing a token as part of the login, but that should not be possible with the login() function in this API. Maybe some kind of caching

Indeed, a token was sent as part of the second login, which caused the problem. I fixed the problem and will open a PR.
