### ISSUE TITLE
API Querying a streampage with a stream slug

### ISSUE THREAD

**Issue by unitrium** [iotile/python_iotile_cloud#64]
Querying a streampage with associated stream seems to be not supported at the moment.

`streampages_raw = self.api.streampage().get(stream=stream['slug'])`
or 
`api/v1/streampage/?stream=some_stream_slug`

returns streampages where stream field is null or stream field close but not an exact match.

**Comment by dkarchmer** [comment]
@RobinetFox Actually, we do support this, only in a different way. You can ask a given stream for its stream pages:

api/v1/stream/slug/streampages/

**Comment by dkarchmer** [comment]
e.g.

https://flex.archfx.io/api/v1/stream/sa--0000-0020--0000-0001-0000-017b--5051/streampages/

**Comment by unitrium** [comment]
Thanks, that solves my problem
